name: aqi_monitor
description: AQI Monitor — ESP32 air quality companion app
version: 0.2.2+4

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.1
  web_socket_channel: ^2.4.0
  http: ^1.2.0
  sqflite: ^2.3.0
  path: ^1.9.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.67.0
  flutter_local_notifications: ^17.0.0
  uuid: ^4.3.3
  cupertino_icons: ^1.0.6
  home_widget: ^0.7.0
  workmanager: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.0

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  fonts:
    - family: SpaceMono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700
